language: python
python:
  - "3.6"
pip3:
  -"9.0.1"
install: "pip install -r requirements.txt"
script:
  - python3.6 test.py
branches:
only:
    - master
notifications:
  email:
    - foksha.alina@phystech.edu
